-- Schema
CREATE SCHEMA IF NOT EXISTS molecular;

-- 1) Raw staging (column-flexible)
DROP TABLE IF EXISTS molecular.disgenet_raw;
CREATE TABLE molecular.disgenet_raw (
  line_no        bigint GENERATED BY DEFAULT AS IDENTITY,
  gene_id_txt    text,
  gene_symbol    text,
  disease_id     text,
  disease_name   text,
  score_txt      text,
  n_pmids_txt    text,
  source         text,
  extra          jsonb DEFAULT '{}'::jsonb
);

-- 2) Normalized associations
DROP TABLE IF EXISTS molecular.disgenet_associations;
CREATE TABLE molecular.disgenet_associations (
  gene_id        integer,           -- NCBI Gene ID
  gene_symbol    text,
  disease_id     text,              -- Typically UMLS CUI (e.g., C#######)
  disease_name   text,
  score          double precision,  -- 0..1
  pmid_count     integer,
  sources        text[],            -- split from 'source'
  loaded_at      timestamptz DEFAULT now()
);

-- Helpful indexes
CREATE INDEX IF NOT EXISTS disgenet_assoc_gene_symbol_idx ON molecular.disgenet_associations (gene_symbol);
CREATE INDEX IF NOT EXISTS disgenet_assoc_gene_id_idx     ON molecular.disgenet_associations (gene_id);
CREATE INDEX IF NOT EXISTS disgenet_assoc_disease_id_idx  ON molecular.disgenet_associations (disease_id);
CREATE INDEX IF NOT EXISTS disgenet_assoc_score_idx       ON molecular.disgenet_associations (score DESC);

-- Optional fuzzy search
CREATE EXTENSION IF NOT EXISTS pg_trgm;
CREATE INDEX IF NOT EXISTS disgenet_assoc_disease_trgm ON molecular.disgenet_associations USING gin (disease_name gin_trgm_ops);
CREATE INDEX IF NOT EXISTS disgenet_assoc_gene_trgm    ON molecular.disgenet_associations USING gin (gene_symbol gin_trgm_ops);

