#!/usr/bin/env python3
"""
PatientTimelineVision Data Models

Python dataclasses matching the PostgreSQL schema.
"""

from dataclasses import dataclass, field
from datetime import datetime, timedelta
from enum import Enum
from typing import Dict, List, Optional, Any


# =============================================================================
# ENUMS (matching schema)
# =============================================================================

class NodeType(str, Enum):
    """Node types in the graph"""
    EVENT = "event"
    MEASUREMENT = "measurement"
    MEDICATION_CHANGE = "medication_change"
    RISK_SIGNAL = "risk_signal"
    NOTE = "note"
    DECISION = "decision"
    DERIVED_INSIGHT = "derived_insight"


class SourceType(str, Enum):
    """Source of node data"""
    RAW = "raw"           # From EHR (ehr.patient_timeline)
    DERIVED = "derived"   # Generated by EoH module
    SYNTHETIC = "synthetic"  # Test data


class NodeStatus(str, Enum):
    """Node status"""
    INCLUDED = "included"      # Active, valid node
    EXCLUDED = "excluded"      # Filtered out
    UNCERTAIN = "uncertain"    # Requires review
    CORRECTED = "corrected"    # Superseded by newer version
    DEPRECATED = "deprecated"  # No longer used


class RelationshipType(str, Enum):
    """Edge relationship types"""
    # Temporal
    TEMPORAL_SEQUENCE = "temporal_sequence"
    TEMPORAL_WINDOW = "temporal_window"
    
    # Causal
    CAUSAL_LIKELY = "causal_likely"
    CAUSAL_POSSIBLE = "causal_possible"
    CAUSAL_PREVENTS = "causal_prevents"
    
    # Semantic
    REFERENCES = "references"
    MODIFIES = "modifies"
    SUPERSEDES = "supersedes"
    
    # Derivation
    DERIVED_FROM = "derived_from"
    COMPOSITE = "composite"
    
    # Similarity
    CORRELATES_WITH = "correlates_with"
    SIMILARITY = "similarity"
    
    # Conflict
    CONTRADICTS = "contradicts"
    
    # Planning
    CARE_PLAN_LINK = "care_plan_link"


# =============================================================================
# NODE DATACLASSES
# =============================================================================

@dataclass
class PatientEventNode:
    """
    Base node in PatientTimelineVision graph.
    
    Immutable after creation (INV-001).
    """
    
    # IDENTITY (required)
    event_id: str
    patient_id: str
    version: int = 1
    
    # CLASSIFICATION (required)
    node_type: NodeType = NodeType.EVENT
    event_subtype: str = ""
    
    # TEMPORAL (required)
    timestamp: datetime = field(default_factory=datetime.utcnow)
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    # SOURCE (required)
    source_type: SourceType = SourceType.RAW
    source_system: str = ""
    
    # STATUS (required)
    status: NodeStatus = NodeStatus.INCLUDED
    
    # PROVENANCE (required, INV-006)
    discovered_by: List[str] = field(default_factory=list)
    
    # DATA (optional)
    structured: Dict[str, Any] = field(default_factory=dict)
    text: str = ""
    
    # ENRICHMENT (optional)
    annotations: Dict[str, Any] = field(default_factory=dict)
    
    # EMBEDDINGS (optional, INV-003)
    embedding_id: Optional[str] = None
    
    # METADATA (optional)
    meta: Dict[str, Any] = field(default_factory=dict)
    
    # LINEAGE (optional, for corrections)
    parent_event_id: Optional[str] = None
    superseded_by_event_id: Optional[str] = None
    
    def __post_init__(self):
        """Validate invariants"""
        if not self.discovered_by:
            raise ValueError("INV-006 violation: discovered_by cannot be empty")
        if self.source_type == SourceType.DERIVED and self.node_type == NodeType.DERIVED_INSIGHT:
            # INV-002 will be validated when edges are added
            pass


@dataclass
class EventRelationshipEdge:
    """
    Edge between two nodes in PatientTimelineVision graph.
    
    Immutable after creation (INV-001).
    """
    
    # IDENTITY (required)
    edge_id: str
    
    # NODES (required)
    source_event_id: str
    target_event_id: str
    
    # CLASSIFICATION (required)
    relationship_type: RelationshipType
    
    # STRENGTH (required)
    strength: float  # 0.0-1.0
    confidence: float  # 0.0-1.0
    
    # PROVENANCE (required, INV-006)
    discovered_by: List[str] = field(default_factory=list)
    created_at: datetime = field(default_factory=datetime.utcnow)
    
    # TEMPORAL (optional)
    time_delta: Optional[timedelta] = None
    
    # ENRICHMENT (optional)
    annotations: Dict[str, Any] = field(default_factory=dict)
    
    # METADATA (optional)
    meta: Dict[str, Any] = field(default_factory=dict)
    
    def __post_init__(self):
        """Validate invariants"""
        if not self.discovered_by:
            raise ValueError("INV-006 violation: discovered_by cannot be empty")
        if not (0.0 <= self.strength <= 1.0):
            raise ValueError(f"strength must be in [0.0, 1.0], got {self.strength}")
        if not (0.0 <= self.confidence <= 1.0):
            raise ValueError(f"confidence must be in [0.0, 1.0], got {self.confidence}")
        if self.source_event_id == self.target_event_id:
            raise ValueError("Self-loops not allowed")


# =============================================================================
# SPECIALIZED NODE TYPES
# =============================================================================

@dataclass
class MeasurementNode(PatientEventNode):
    """Lab result, vital sign, or other measurement"""
    
    def __post_init__(self):
        super().__post_init__()
        self.node_type = NodeType.MEASUREMENT
        
        # Validate required structured fields
        if not self.structured.get("test_name"):
            raise ValueError("MeasurementNode requires structured.test_name")
        if "value" not in self.structured:
            raise ValueError("MeasurementNode requires structured.value")


@dataclass
class MedicationChangeNode(PatientEventNode):
    """Medication start, stop, or dose change"""
    
    def __post_init__(self):
        super().__post_init__()
        self.node_type = NodeType.MEDICATION_CHANGE
        
        # Validate required structured fields
        if not self.structured.get("drug_name"):
            raise ValueError("MedicationChangeNode requires structured.drug_name")
        if not self.structured.get("action"):
            raise ValueError("MedicationChangeNode requires structured.action")


@dataclass
class RiskSignalNode(PatientEventNode):
    """Risk flag or prediction"""
    
    def __post_init__(self):
        super().__post_init__()
        self.node_type = NodeType.RISK_SIGNAL
        
        # Validate required structured fields
        if not self.structured.get("signal_type"):
            raise ValueError("RiskSignalNode requires structured.signal_type")
        if not self.structured.get("risk_level"):
            raise ValueError("RiskSignalNode requires structured.risk_level")


@dataclass
class DerivedInsightNode(PatientEventNode):
    """EoH-generated insight (composite node)"""
    
    def __post_init__(self):
        super().__post_init__()
        self.node_type = NodeType.DERIVED_INSIGHT
        self.source_type = SourceType.DERIVED
        
        # Validate required structured fields (INV-002)
        if not self.structured.get("insight_type"):
            raise ValueError("DerivedInsightNode requires structured.insight_type")
        if not self.structured.get("insight_summary"):
            raise ValueError("DerivedInsightNode requires structured.insight_summary")
        if "confidence" not in self.structured:
            raise ValueError("DerivedInsightNode requires structured.confidence")
        if not self.structured.get("contributing_event_ids"):
            raise ValueError("DerivedInsightNode requires structured.contributing_event_ids (INV-002)")

